export const INCREMENT_ACTION_TYPE = 'INCREMENT_ACTION_TYPE'
export type INCREMENT_ACTION_TYPE= typeof INCREMENT_ACTION_TYPE

export const DECREMENT_ACTION_TYPE  = 'DECREMENT_ACTION_TYPE'
export type DECREMENT_ACTION_TYPE = typeof DECREMENT_ACTION_TYPE